### ISSUE TITLE
UserWarning and TypeError in rockfish inference command

### ISSUE THREAD

**Issue by PengNi** [lbcb-sci/rockfish#11]
Hi, dear developers,

great tool for methylation detection! I am trying rockfish, however, I got the following UserWarning and Errors in `rockfish inference`:
```
Parsing reference file genome/human/chm13v2.0.fa
Building reference positions for the given motif.
/public/home/hpc174601028/.conda/envs/rockfish/lib/python3.9/site-packages/pytorch_lightning/core/saving.py:208: UserWarning: Found keys that are in the model state dict but not in the checkpoint: ['codebook.weight', 'fc_mask.weight', 'fc_mask.bias']
  rank_zero_warn(
0it [07:20, ?it/s]
Traceback (most recent call last):
  File "/public/home/hpc174601028/.conda/envs/rockfish/bin/rockfish", line 8, in <module>
    sys.exit(main())
  File "/public/home/hpc174601028/.conda/envs/rockfish/lib/python3.9/site-packages/rockfish/__main__.py", line 66, in main
    args.func(args)
  File "/public/home/hpc174601028/.conda/envs/rockfish/lib/python3.9/site-packages/rockfish/model/inference.py", line 231, in inference
    out = model(signals, r_mappings, q_mappings, bases, n_blocks)
  File "/public/home/hpc174601028/.conda/envs/rockfish/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/public/home/hpc174601028/.conda/envs/rockfish/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/public/home/hpc174601028/.conda/envs/rockfish/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/public/home/hpc174601028/.conda/envs/rockfish/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/public/home/hpc174601028/.conda/envs/rockfish/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 108, in parallel_apply
    output.reraise()
  File "/public/home/hpc174601028/.conda/envs/rockfish/lib/python3.9/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/public/home/hpc174601028/.conda/envs/rockfish/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in _worker
    output = module(*input, **kwargs)
  File "/public/home/hpc174601028/.conda/envs/rockfish/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/public/home/hpc174601028/.conda/envs/rockfish/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/public/home/hpc174601028/.conda/envs/rockfish/lib/python3.9/site-packages/rockfish/model/model.py", line 119, in forward
    signal = self.signal_encoder(signal, src_key_padding_mask=signal_mask)
  File "/public/home/hpc174601028/.conda/envs/rockfish/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/public/home/hpc174601028/.conda/envs/rockfish/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'src_key_padding_mask'
```

The command I use is:
```
CUDA_VISIBLE_DEVICES=0,1 /usr/bin/time -v rockfish inference -i fast5s_gpy \
  --reference genome/human/chm13v2.0.fa \
  --model_path /public/home/hpc174601028/tools/rockfish/models/rf-base.pt \
  -r -t 32 -b 8192 -d 0,1 -o rockfish.inference/predictions.tsv \
  > rockfish.inference/predictions.log 2>&1
```

May you tell what the issue is here?

Thanks in advance!

Best,
Peng

**Comment by PengNi** [comment]
Just removing `src_key_padding_mask=` in the `model.py` file will make it work.
